// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRgk-ryR3b2i3GDlHnkYv3obfORJ6oo8',
    appId: '1:1065743042513:web:46b17ff8d5d3b896f442f0',
    messagingSenderId: '1065743042513',
    projectId: 'newbeefly-d324b',
    authDomain: 'newbeefly-d324b.firebaseapp.com',
    storageBucket: 'newbeefly-d324b.appspot.com',
    measurementId: 'G-T1J7ZD71VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKN8DY3m5dwRXWIArYzuPue6Aaw_2cnvM',
    appId: '1:1065743042513:android:25ec66783dd51aa7f442f0',
    messagingSenderId: '1065743042513',
    projectId: 'newbeefly-d324b',
    storageBucket: 'newbeefly-d324b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaaL25XCP9yluTBaSZzZ7Rer4I0yW9Eek',
    appId: '1:1065743042513:ios:ecf920e9deea4a45f442f0',
    messagingSenderId: '1065743042513',
    projectId: 'newbeefly-d324b',
    storageBucket: 'newbeefly-d324b.appspot.com',
    iosClientId: '1065743042513-r19btgn41o0mrepu86u9a967ur54rju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.newbeefly',
  );
}
